apiVersion: v1
kind: Service
metadata:
  name: load-balancer-svc
spec:
  type: LoadBalancer
  selector:
    app: backend #associate this saervice with label this pod
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80
