apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  DB_HOST: "172.31.10.30:3306"
  DB_USER: "dbadmin"
  DB_PASS: "db!2312$#"
  APP_MODE: "production"
  APP_CAPACITY: "100%"
  large-data: |
    This is Line 1
    This is Line 2
    This is Line 3



# apiVersion: v1
# kind: Pod
# metadata:
#   name: configmap-volume-pod
# spec:
#   containers:
#     - name: nginx-container
#       image: nginx
#       volumeMounts:
#         - name: config-volume
#           mountPath: /etc/config
#   volumes:
#     - name: config-volume
#       configMap:
#         name: demo-configmap # mount our pod with volumes config-volume 


