# apiVersion: v1
# kind: Pod
# metadata:
#   name: kplabs-pod
#   labels:
#     name: myapp
# spec:
#   nodeselector: 
#     size: Large
#   containers:
#   - name: nginx-container
#     image: nginx 





# apiVersion: v1
# kind: Pod
# metadata:
#   name: kplabs-pod
#   labels:
#     name: myapp
# spec:
#   nodeSelector:    # Ensures the pod runs on a node with "size=Large"
#     size: Large
#   containers:
#   - name: nginx-container
#     image: nginx




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: myapp
# spec: 
#   replicas: 3 
#   selector:
#     matchLabels:
#       app: myapp
#   template:
#     metadata:
#       labels:
#         app: myapp
#     spec:
#       containers:
#       - name: nginx-container
#         image: nginx 
       



apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      nodeSelector:
        size: Large
      containers:
      - name: nginx-pod
        image: nginx