# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-pod
#   labels:
#     name: myapp
# spec:
#   containers:
#   - name: nginx-container
#     image: nginx



apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx 