apiVersion: v1
kind: Pod
metadata:
  name: new-ping-pod
  labels:
    name: app
spec:
  containers:
  - name: ping-container
    image: busybox
    command: [ "ping" ]
    args: [ "-c","60","google.com" ] 