apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: nginx-container
    image: nginx 
    resources:
      requests: 
        memory: '400Mi'
        cpu: '0.1'
      limits:
        memory: "500Mi"
        cpu: "1"
 