apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
spec:
  containers:
  - name: nginx-container
    image: nginx
    command: ["nginx", "-g", "daemon off;"]
    args: ["-c", "/etc/nginx/nginx.conf"]
    ports:
    - containerPort: 8080
