apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: auth-secret # Replace with your actual secret name
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret-volume"
